# Python Learning Roadmap All Blocks

### GET Request

In [1]:
import requests
r = requests.get("https://picsum.photos/v2/list")
r

<Response [200]>

### Shows the status of the code

In [2]:
r.status_code

200


### Displays only the first 300 characters of the response content

In [3]:
r.text[0:300]

'[{"id":"0","author":"Alejandro Escamilla","width":5000,"height":3333,"url":"https://unsplash.com/photos/yC-Yzbqy7PY","download_url":"https://picsum.photos/id/0/5000/3333"},{"id":"1","author":"Alejandro Escamilla","width":5000,"height":3333,"url":"https://unsplash.com/photos/LNRyGwIJr5c","download_ur'

### Headers = information about the answer

In [4]:
my_headers = r.headers
my_headers

{'Date': 'Tue, 18 Nov 2025 12:19:20 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'cloudflare', 'access-control-expose-headers': 'Link', 'Cache-Control': 'private, no-cache, no-store, must-revalidate', 'link': '<https://picsum.photos/v2/list?page=2&limit=30>; rel="next"', 'vary': 'Origin', 'cf-cache-status': 'DYNAMIC', 'Nel': '{"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}', 'Strict-Transport-Security': 'max-age=15552000', 'X-Content-Type-Options': 'nosniff', 'Report-To': '{"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=lvTkwNKEgWn8nrPwgCkBStLb8TMcrI3s5d8Vr4tEYvkMnEjCiU4ofli9oOWwNTpU%2FHFPqFpoq8L75%2BXFn5g%2F3Q4qmGS70DNzngf8zQ%3D%3D"}]}', 'Content-Encoding': 'br', 'CF-RAY': '9a076a661f76b725-MAD', 'alt-svc': 'h3=":443"; ma=86400'}

In [5]:
my_headers["Content-Type"]


'application/json'

### GET request with parameters

In [6]:
params = {"name" : "Dani" , "City": "Barcelona"}

In [7]:
r = requests.get("https://picsum.photos/v2/list" , params = params)

In [8]:
r.url

'https://picsum.photos/v2/list?name=Dani&City=Barcelona'

In [9]:
r.json()

[{'id': '0',
  'author': 'Alejandro Escamilla',
  'width': 5000,
  'height': 3333,
  'url': 'https://unsplash.com/photos/yC-Yzbqy7PY',
  'download_url': 'https://picsum.photos/id/0/5000/3333'},
 {'id': '1',
  'author': 'Alejandro Escamilla',
  'width': 5000,
  'height': 3333,
  'url': 'https://unsplash.com/photos/LNRyGwIJr5c',
  'download_url': 'https://picsum.photos/id/1/5000/3333'},
 {'id': '2',
  'author': 'Alejandro Escamilla',
  'width': 5000,
  'height': 3333,
  'url': 'https://unsplash.com/photos/N7XodRrbzS0',
  'download_url': 'https://picsum.photos/id/2/5000/3333'},
 {'id': '3',
  'author': 'Alejandro Escamilla',
  'width': 5000,
  'height': 3333,
  'url': 'https://unsplash.com/photos/Dl6jeyfihLk',
  'download_url': 'https://picsum.photos/id/3/5000/3333'},
 {'id': '4',
  'author': 'Alejandro Escamilla',
  'width': 5000,
  'height': 3333,
  'url': 'https://unsplash.com/photos/y83Je1OC6Wc',
  'download_url': 'https://picsum.photos/id/4/5000/3333'},
 {'id': '5',
  'author': 'Alej

In [10]:
r.text

'[{"id":"0","author":"Alejandro Escamilla","width":5000,"height":3333,"url":"https://unsplash.com/photos/yC-Yzbqy7PY","download_url":"https://picsum.photos/id/0/5000/3333"},{"id":"1","author":"Alejandro Escamilla","width":5000,"height":3333,"url":"https://unsplash.com/photos/LNRyGwIJr5c","download_url":"https://picsum.photos/id/1/5000/3333"},{"id":"2","author":"Alejandro Escamilla","width":5000,"height":3333,"url":"https://unsplash.com/photos/N7XodRrbzS0","download_url":"https://picsum.photos/id/2/5000/3333"},{"id":"3","author":"Alejandro Escamilla","width":5000,"height":3333,"url":"https://unsplash.com/photos/Dl6jeyfihLk","download_url":"https://picsum.photos/id/3/5000/3333"},{"id":"4","author":"Alejandro Escamilla","width":5000,"height":3333,"url":"https://unsplash.com/photos/y83Je1OC6Wc","download_url":"https://picsum.photos/id/4/5000/3333"},{"id":"5","author":"Alejandro Escamilla","width":5000,"height":3334,"url":"https://unsplash.com/photos/LF8gK8-HGSg","download_url":"https://pic

### Request to an endpoint to return JSON

In [11]:
r = requests.get("https://api.adviceslip.com/advice")
r.text

'{"slip": { "id": 204, "advice": "The best nights out are when people around you are simply having fun."}}'

In [12]:
r.url

'https://api.adviceslip.com/advice'

In [13]:
r.json()

{'slip': {'id': 204,
  'advice': 'The best nights out are when people around you are simply having fun.'}}

In [14]:
r

<Response [200]>

In [15]:
type(r.text)

str

In [16]:
type(r.json())

dict

### Access specific keys within the JSON

In [17]:
r = requests.get("https://httpbin.org/get",  params ={"name": "Dani", "city" : "Barcelona"})

In [18]:
r_json = r.json()

In [19]:
r_json

{'args': {'city': 'Barcelona', 'name': 'Dani'},
 'headers': {'Accept': '*/*',
  'Accept-Encoding': 'gzip, deflate, br, zstd',
  'Host': 'httpbin.org',
  'User-Agent': 'python-requests/2.32.3',
  'X-Amzn-Trace-Id': 'Root=1-691c6449-3c7b8c3568adad152b2dcf70'},
 'origin': '83.42.140.122',
 'url': 'https://httpbin.org/get?name=Dani&city=Barcelona'}

In [20]:
r_json["args"]

{'city': 'Barcelona', 'name': 'Dani'}

In [21]:
r_json["args"]["city"]

'Barcelona'

In [22]:
r_json["headers"]

{'Accept': '*/*',
 'Accept-Encoding': 'gzip, deflate, br, zstd',
 'Host': 'httpbin.org',
 'User-Agent': 'python-requests/2.32.3',
 'X-Amzn-Trace-Id': 'Root=1-691c6449-3c7b8c3568adad152b2dcf70'}

In [23]:
r_json["url"]

'https://httpbin.org/get?name=Dani&city=Barcelona'

### Request to a made-up URL + try/except

In [24]:
try:
    r = requests.get("https://paginaquenoexiste123456.com")
    print(r.status_code)
except requests.exceptions.RequestException as e:
    print("❌ Error al hacer la petición:", e)


❌ Error al hacer la petición: HTTPSConnectionPool(host='paginaquenoexiste123456.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x109f6f250>: Failed to resolve 'paginaquenoexiste123456.com' ([Errno 8] nodename nor servname provided, or not known)"))


### More requests

In [25]:
params = {"Nombre": "Luis" , "Apellido": "Garcia"}
r = requests.get("https://dog.ceo/api/breeds/image/random" , params = params)

In [26]:
r.status_code

200

In [27]:
r.text[:200]

'{"message":"https:\\/\\/images.dog.ceo\\/breeds\\/havanese\\/00100trPORTRAIT_00100_BURST20191222103956878_COVER.jpg","status":"success"}'

In [28]:
r.headers["content-type"]

'application/json'

In [29]:
r.headers["date"]

'Tue, 18 Nov 2025 12:19:23 GMT'

In [30]:
r.headers["content-type"]

'application/json'

In [31]:
r.headers["server"]

'cloudflare'

In [32]:
r = requests.get("https://picsum.photos/v2/list" , params = {"name" : "Dani" , "age": 24 , "city":"Barcelona"})


In [33]:
r.text

'[{"id":"0","author":"Alejandro Escamilla","width":5000,"height":3333,"url":"https://unsplash.com/photos/yC-Yzbqy7PY","download_url":"https://picsum.photos/id/0/5000/3333"},{"id":"1","author":"Alejandro Escamilla","width":5000,"height":3333,"url":"https://unsplash.com/photos/LNRyGwIJr5c","download_url":"https://picsum.photos/id/1/5000/3333"},{"id":"2","author":"Alejandro Escamilla","width":5000,"height":3333,"url":"https://unsplash.com/photos/N7XodRrbzS0","download_url":"https://picsum.photos/id/2/5000/3333"},{"id":"3","author":"Alejandro Escamilla","width":5000,"height":3333,"url":"https://unsplash.com/photos/Dl6jeyfihLk","download_url":"https://picsum.photos/id/3/5000/3333"},{"id":"4","author":"Alejandro Escamilla","width":5000,"height":3333,"url":"https://unsplash.com/photos/y83Je1OC6Wc","download_url":"https://picsum.photos/id/4/5000/3333"},{"id":"5","author":"Alejandro Escamilla","width":5000,"height":3334,"url":"https://unsplash.com/photos/LF8gK8-HGSg","download_url":"https://pic

In [34]:
r.json()

[{'id': '0',
  'author': 'Alejandro Escamilla',
  'width': 5000,
  'height': 3333,
  'url': 'https://unsplash.com/photos/yC-Yzbqy7PY',
  'download_url': 'https://picsum.photos/id/0/5000/3333'},
 {'id': '1',
  'author': 'Alejandro Escamilla',
  'width': 5000,
  'height': 3333,
  'url': 'https://unsplash.com/photos/LNRyGwIJr5c',
  'download_url': 'https://picsum.photos/id/1/5000/3333'},
 {'id': '2',
  'author': 'Alejandro Escamilla',
  'width': 5000,
  'height': 3333,
  'url': 'https://unsplash.com/photos/N7XodRrbzS0',
  'download_url': 'https://picsum.photos/id/2/5000/3333'},
 {'id': '3',
  'author': 'Alejandro Escamilla',
  'width': 5000,
  'height': 3333,
  'url': 'https://unsplash.com/photos/Dl6jeyfihLk',
  'download_url': 'https://picsum.photos/id/3/5000/3333'},
 {'id': '4',
  'author': 'Alejandro Escamilla',
  'width': 5000,
  'height': 3333,
  'url': 'https://unsplash.com/photos/y83Je1OC6Wc',
  'download_url': 'https://picsum.photos/id/4/5000/3333'},
 {'id': '5',
  'author': 'Alej

In [35]:
data = r.json()
data[0]

{'id': '0',
 'author': 'Alejandro Escamilla',
 'width': 5000,
 'height': 3333,
 'url': 'https://unsplash.com/photos/yC-Yzbqy7PY',
 'download_url': 'https://picsum.photos/id/0/5000/3333'}

In [36]:
data[1:2]

[{'id': '1',
  'author': 'Alejandro Escamilla',
  'width': 5000,
  'height': 3333,
  'url': 'https://unsplash.com/photos/LNRyGwIJr5c',
  'download_url': 'https://picsum.photos/id/1/5000/3333'}]

### def Analyze HTTP response from a URL

In [37]:
def healthy_url (url):
    r = requests.get(url)
    status = r.status_code
    type  = r.headers.get("Content-Type" , "not found")
    content_lenght = r.headers.get("Content-Length" , "not found")
    print(f"El estatus del contenido {status}")
    print(f"El type del contenido {type}") 
    print(f"La longitud del contenido {content_lenght}")



## With Open

In [38]:
with open("notas.txt", "w", encoding="utf-8") as f:
    f.write("Primera línea\n")
    f.write("Segunda línea\n")
    f.write("Tercera línea\n")

In [39]:
with open ("notas.txt", "r" , encoding ="UTF-8" ) as f :
    read = f.read()
print(read)

Primera línea
Segunda línea
Tercera línea



In [40]:
with open ("notas.txt", "r" , encoding ="UTF-8" ) as f :
    for line in f:
        print(line)

Primera línea

Segunda línea

Tercera línea



In [41]:
lineas_validas = []
with open ("notas.txt", "r" , encoding = "UTF-8" ) as f :
    for line in f :
        if line.strip() != "":
            lineas_validas.append(line.strip())
print(lineas_validas)


['Primera línea', 'Segunda línea', 'Tercera línea']


In [42]:
with open ("notas.txt", "a" , encoding = "UTF-8" ) as f :
    f.write("i am fine thank you")

In [43]:
with open ("notas.txt", "r" , encoding="UTF-8") as f:
    read = f.read()
print(read)


Primera línea
Segunda línea
Tercera línea
i am fine thank you


In [44]:
with open("origen.txt", "w", encoding="UTF-8") as f:
    f.write("my first friend\n")
    f.write("my second friend\n")
    f.write("my only friend\n")

with open("origen.txt", "r", encoding="UTF-8") as f1:
    with open("copia.txt", "w", encoding="UTF-8") as f2:
        for line in f1:
            f2.write(line)

print("Copy completed successfully")


Copy completed successfully


In [45]:
with open ("notas.txt", "r", encoding = "UTF-8") as notas , \
    open ("origen.txt", "r", encoding = "UTF-8") as origen , \
    open ("fusion.txt", "w", encoding = "UTF-8") as fusion :
    fusion.write(notas.read())
    fusion.write("\n----------------------------------------\n")
    fusion.write(origen.read())


In [46]:
with open ("create.txt" , "w" , encoding = "UTF-8") as c :
    c.write(",Hello everybody,")
    c.write("Hello everyone")

with open ("create.txt" , "r" , encoding = "UTF-8") as c :
    read = c.read()
read
    

',Hello everybody,Hello everyone'

In [47]:
with open ("create.txt" , "r" , encoding = "UTF-8") as c , \
    open("newcopy.txt" , "w" , encoding = "UTF-8") as new :
        for i in c :
            new.write(i)

    
    

In [48]:
with open ("create.txt" , "r" , encoding = "UTF-8") as a , \
     open ("newcopy.txt" , "r" , encoding = "UTF-8") as b , \
     open ("newnew.txt" , "w" , encoding = "UTF-8") as c :
         c.write(a.read())
         c.write("\n................................\n")
         c.write(b.read())

In [49]:
with open ( "newnew.txt","r",encoding = "UTF-8") as newnew, \
     open ("newhello.txt", "w", encoding = "UTF-8") as hello :
         for i in newnew:
             if "Hello" in i or "hello" in i:
                 hello.write(i)

In [50]:
with open("newhello.txt", "r", encoding="UTF-8") as newhello, \
     open("nexthello.txt", "w", encoding="UTF-8") as next:
    caract = 0
    lines = 0
    for line in newhello:
        caract += len(line)
        lines += 1
        next.write(line)
    next.write(str(caract))
    next.write(str(lines))


In [ ]:
my_document = input("Enter your file name: ")
things = ""

while True:
    
    print("\nWelcome to the Note System!")
    print("What do you want to do? Select an option 1 - 4")
    print("1 - Add a new note")
    print("2 - Show all notes")
    print("3 - Count how many notes there are")
    print("4 - Exit")
    my_number = input("Choose an option (1-2-3-4): ")

    if my_number == "1":
        things = input("What note do you want to add? ")
        with open(my_document, "a", encoding="UTF-8") as add:
            add.write(things + "\n")
        print(f"Perfect, '{things}' added.")

    elif my_number == "2":
        print("\n=== YOUR NOTES ===")
        with open(my_document, "r", encoding="UTF-8") as f:
            for line in f:
                print(line.strip())

    elif my_number == "3":
        counts = 0
        with open(my_document, "r", encoding="UTF-8") as f:
            for _ in f:
                counts += 1
        print(f"\nThere are {counts} notes.")

    elif my_number == "4":
        print("Exiting the app, see you soon!")
        break

    else:
        print("Invalid option, try again.")


## NUMPY 1D

In [ ]:
import numpy as np
n_array = np.array([1,2,3,4,5,6,7,8,9,10])
n_array = np.arange(1,11)
n_array =np.linspace(1,10,10)

In [ ]:
type(n_array)

numpy.ndarray

In [ ]:
n_array.dtype

dtype('float64')

In [ ]:
n_array.shape

(10,)

In [ ]:
n_array.size

10

In [ ]:
n_array.ndim

1

In [ ]:
n_array[-3:] = 0

In [ ]:
n2_array = np.arange(10, 0, -1)
n3_array = np.arange(1,11)
f_array = n2_array + n3_array
f_array

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [ ]:
f_array.sum()

np.int64(110)

In [ ]:
f_array.mean()

np.float64(11.0)

In [ ]:
f_array.max()

np.int64(11)

In [ ]:
f_array.min()

np.int64(11)

In [ ]:
wow_array = np.arange(0,101,1)
wow_array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
wow_array.mean()

np.float64(50.0)

In [ ]:
wow_array.sum()

np.int64(5050)

In [ ]:
wow_array.max()

np.int64(100)

In [ ]:
wow_array.min()

np.int64(0)

In [ ]:
wow_array[wow_array > 50] = 0
wow_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [ ]:
m1 = np.array([29,1,56,2,11,45,4,76])
m2 = np.array([31,22,48,9,34,66,2,81])
m3 = m1 + m2
m4 = m1 * m2
m4

array([ 899,   22, 2688,   18,  374, 2970,    8, 6156])

In [ ]:
students_notes = np.array([3,7,5,6,2,1,9,6,7,7,5,5,5,6,7,9,9,6,8,6])

In [ ]:
aprobados = np.sum(students_notes >= 5)
aprobados

np.int64(17)

In [ ]:
suspendidos = np.sum(students_notes < 5)
suspendidos

np.int64(3)

In [ ]:
max_note = np.max(students_notes)
max_note

np.int64(9)

## NUMPY 2D

In [ ]:
n2 = np.arange(1,7).reshape(2,3)
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
n2.shape

(2, 3)

In [ ]:
n2.ndim

2

In [ ]:
type(n2)

numpy.ndarray

In [ ]:
n2.dtype

dtype('int64')

In [ ]:
n2[0,2]

np.int64(3)

In [ ]:
n2[0]

array([1, 2, 3])

In [ ]:
n2[: , 0]

array([1, 4])

In [ ]:
n2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
num_school = np.arange(1,13)
num_school.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
num_school = num_school +1
num_school

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
array3x3 = np.arange(1,10).reshape(3,3)
array3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
diag = array3x3.diagonal()
diag

array([1, 5, 9])

In [ ]:
sum_all = array3x3.sum(axis=1)
sum_all

array([ 6, 15, 24])

In [ ]:
sum_all2 = array3x3.sum(axis=0)
sum_all2

array([12, 15, 18])

In [ ]:
array3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array3x3.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
temperaturas = np.random.randint(10, 35, size=(7, 24))
temperaturas

array([[10, 28, 21, 10, 13, 24, 26, 17, 14, 23, 23, 10, 26, 28, 24, 19,
        19, 19, 17, 13, 26, 24, 25, 27],
       [11, 13, 28, 15, 13, 29, 33, 23, 25, 14, 10, 15, 26, 11, 21, 19,
        16, 28, 33, 31, 15, 14, 10, 30],
       [19, 23, 13, 10, 34, 15, 28, 19, 16, 25, 15, 21, 32, 13, 10, 22,
        19, 22, 21, 14, 15, 10, 21, 26],
       [25, 31, 10, 32, 28, 34, 24, 18, 22, 16, 20, 13, 21, 12, 14, 13,
        32, 30, 10, 12, 22, 29, 27, 25],
       [22, 22, 28, 16, 29, 25, 12, 28, 14, 29, 19, 18, 26, 15, 25, 22,
        25, 34, 20, 12, 32, 21, 11, 34],
       [27, 32, 22, 10, 30, 30, 26, 31, 27, 10, 30, 12, 22, 22, 19, 12,
        14, 20, 19, 24, 21, 32, 27, 26],
       [19, 12, 27, 28, 16, 25, 17, 29, 26, 34, 22, 27, 27, 23, 33, 19,
        33, 19, 30, 29, 20, 32, 31, 19]])

In [ ]:
temperaturas.mean(axis = 1)

array([20.25      , 20.125     , 19.29166667, 21.66666667, 22.45833333,
       22.70833333, 24.875     ])

In [ ]:
temperaturas.mean(axis = 0)

array([19.        , 23.        , 21.28571429, 17.28571429, 23.28571429,
       26.        , 23.71428571, 23.57142857, 20.57142857, 21.57142857,
       19.85714286, 16.57142857, 25.71428571, 17.71428571, 20.85714286,
       18.        , 22.57142857, 24.57142857, 21.42857143, 19.28571429,
       21.57142857, 23.14285714, 21.71428571, 26.71428571])

In [ ]:
max_temp = temperaturas.max()
print(max_temp)

34


In [ ]:
indice_plano = temperaturas.argmax()
print(indice_plano)

52


In [ ]:
dia_max, hora_max = np.unravel_index(indice_plano, temperaturas.shape)

In [ ]:
print(dia_max)

2


In [ ]:
print(hora_max)

4


## Pandas

In [ ]:
import pandas as pd

In [ ]:
persons = {"Name":["Dani","Olga","Jaime","Sandra","Ivan","Lucia"], "Age": [24,26,21,31,33,25] , "City": ["Barcelona", "Londres", "Berlin" , "Dublin" , "Madrid", "Miami"]}
psn = pd.DataFrame(persons)
print(persons)

{'Name': ['Dani', 'Olga', 'Jaime', 'Sandra', 'Ivan', 'Lucia'], 'Age': [24, 26, 21, 31, 33, 25], 'City': ['Barcelona', 'Londres', 'Berlin', 'Dublin', 'Madrid', 'Miami']}


In [ ]:
psn[:3]

Name  Age       City
0   Dani   24  Barcelona
1   Olga   26    Londres
2  Jaime   21     Berlin

In [ ]:
psn[-2:]

Name  Age    City
4   Ivan   33  Madrid
5  Lucia   25   Miami

In [ ]:
psn.iloc[0]

Name         Dani
Age            24
City    Barcelona
Name: 0, dtype: object

In [ ]:
psn.iloc[2:5]

Name  Age    City
2   Jaime   21  Berlin
3  Sandra   31  Dublin
4    Ivan   33  Madrid

In [ ]:
psn.iloc[:,1]

0    24
1    26
2    21
3    31
4    33
5    25
Name: Age, dtype: int64

In [ ]:
psn.loc[:, ["Name", "Age"]]


Name  Age
0    Dani   24
1    Olga   26
2   Jaime   21
3  Sandra   31
4    Ivan   33
5   Lucia   25

In [ ]:
psn[psn["Age"] > 25]


Name  Age     City
1    Olga   26  Londres
3  Sandra   31   Dublin
4    Ivan   33   Madrid

In [ ]:
psn["City"].unique()

array(['Barcelona', 'Londres', 'Berlin', 'Dublin', 'Madrid', 'Miami'],
      dtype=object)

In [ ]:
psn.sort_values("Age", ascending=False)

Name  Age       City
4    Ivan   33     Madrid
3  Sandra   31     Dublin
1    Olga   26    Londres
5   Lucia   25      Miami
0    Dani   24  Barcelona
2   Jaime   21     Berlin

In [ ]:
psn.to_csv("people.csv", index=False)

In [ ]:
new = pd.read_csv("people.csv")
new

Name  Age       City
0    Dani   24  Barcelona
1    Olga   26    Londres
2   Jaime   21     Berlin
3  Sandra   31     Dublin
4    Ivan   33     Madrid
5   Lucia   25      Miami

In [ ]:
student = {"Name": ["Alex", "Ivan", "Miquel","Liam","Laura"], "Note": [7,5,6,5,4] , "Group": ["A","B","A","C","D"]}
st = pd.DataFrame(student)
st

Name  Note Group
0    Alex     7     A
1    Ivan     5     B
2  Miquel     6     A
3    Liam     5     C
4   Laura     4     D

In [ ]:
st[st["Note"] >= 5]

Name  Note Group
0    Alex     7     A
1    Ivan     5     B
2  Miquel     6     A
3    Liam     5     C

In [ ]:
st.groupby("Group").size()

Group
A    2
B    1
C    1
D    1
dtype: int64

In [ ]:
st.sort_values("Note", ascending=False)


Name  Note Group
0    Alex     7     A
2  Miquel     6     A
1    Ivan     5     B
3    Liam     5     C
4   Laura     4     D

In [ ]:
st.to_csv("sudents.csv", index=False)

In [ ]:
stud = pd.read_csv("people.csv")
stud

Name  Age       City
0    Dani   24  Barcelona
1    Olga   26    Londres
2   Jaime   21     Berlin
3  Sandra   31     Dublin
4    Ivan   33     Madrid
5   Lucia   25      Miami

In [ ]:
productos = {
    "nombre": ["Teclado", "Camiseta", "Gorra", "Ratón", "Pantalón", "Monitor", "Mochila"],
    "categoria": ["Electrónica", "Ropa", "Accesorios", "Electrónica", "Ropa", "Electrónica", "Accesorios"],
    "precio": [25.99, 12.50, 8.99, 17.49, 29.99, 199.99, 45.00],
    "stock": [12, 40, 0, 30, 15, 0, 50]
}

pr = pd.DataFrame(productos)
pr

nombre    categoria  precio  stock
0   Teclado  Electrónica   25.99     12
1  Camiseta         Ropa   12.50     40
2     Gorra   Accesorios    8.99      0
3     Ratón  Electrónica   17.49     30
4  Pantalón         Ropa   29.99     15
5   Monitor  Electrónica  199.99      0
6   Mochila   Accesorios   45.00     50

In [ ]:
pr[pr["stock"] <= 0]

nombre    categoria  precio  stock
2    Gorra   Accesorios    8.99      0
5  Monitor  Electrónica  199.99      0

In [ ]:

precio_medio = pr["precio"].mean()
pr[pr["precio"] > precio_medio]

nombre    categoria  precio  stock
5  Monitor  Electrónica  199.99      0

In [ ]:
pr.nlargest(3, "precio")

nombre    categoria  precio  stock
5   Monitor  Electrónica  199.99      0
6   Mochila   Accesorios   45.00     50
4  Pantalón         Ropa   29.99     15

In [ ]:
pr.groupby("categoria")["nombre"].count()


categoria
Accesorios     2
Electrónica    3
Ropa           2
Name: nombre, dtype: int64