# Training With Pandas

### Import pandas and save the file

In [13]:
import pandas as pd 
csv_file = "songs.csv"
pd_songs = pd.read_csv(csv_file)
print(pd_songs)

            Artist                      Album  Released    Length
0  Michael Jackson                   Thriller      1982  00:42:19
1            AC/DC              Back in Black      1980  00:42:11
2       Pink Floyd  The Dark Side of the Moon      1973  00:42:49
3  Whitney Houston              The Bodyguard      1992  00:57:44
4        Meat Loaf            Bat Out of Hell      1977  00:46:33


In [16]:
pd_songs.head()

Artist                      Album  Released    Length
0  Michael Jackson                   Thriller      1982  00:42:19
1            AC/DC              Back in Black      1980  00:42:11
2       Pink Floyd  The Dark Side of the Moon      1973  00:42:49
3  Whitney Houston              The Bodyguard      1992  00:57:44
4        Meat Loaf            Bat Out of Hell      1977  00:46:33

In [18]:
pd_songs.tail(1)

Artist            Album  Released    Length
4  Meat Loaf  Bat Out of Hell      1977  00:46:33

In [22]:
pd_songs.shape

(5, 4)

In [23]:
pd_songs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Artist    5 non-null      object
 1   Album     5 non-null      object
 2   Released  5 non-null      int64 
 3   Length    5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes


In [24]:
pd_songs.describe()

Released
count     5.000000
mean   1980.800000
std       7.120393
min    1973.000000
25%    1977.000000
50%    1980.000000
75%    1982.000000
max    1992.000000

### Object Type = Series []

In [25]:
pd_songs["Album"]

0                     Thriller
1                Back in Black
2    The Dark Side of the Moon
3                The Bodyguard
4              Bat Out of Hell
Name: Album, dtype: object

### Object Type = DataFrame [[]]

In [29]:
pd_songs[["Album"]]

Album
0                   Thriller
1              Back in Black
2  The Dark Side of the Moon
3              The Bodyguard
4            Bat Out of Hell

In [30]:
pd_songs[["Album", "Released"]]

Album  Released
0                   Thriller      1982
1              Back in Black      1980
2  The Dark Side of the Moon      1973
3              The Bodyguard      1992
4            Bat Out of Hell      1977

### .iloc (integer location ) return like a Serie

In [35]:
pd_songs.iloc[0]

Artist      Michael Jackson
Album              Thriller
Released               1982
Length             00:42:19
Name: 0, dtype: object

In [36]:
pd_songs.iloc[[0]]

Artist     Album  Released    Length
0  Michael Jackson  Thriller      1982  00:42:19

### .iloc [[]] Return like a DataFrame

In [41]:
pd_songs.iloc[[0]]

Artist     Album  Released    Length
0  Michael Jackson  Thriller      1982  00:42:19

### .loc (location by label) return like a Serie

In [33]:
pd_songs.loc[1]


Artist              AC/DC
Album       Back in Black
Released             1980
Length           00:42:11
Name: 1, dtype: object

### .loc [[]] Return like a DataFrame

In [40]:
pd_songs.loc[[1]]

Artist          Album  Released    Length
1  AC/DC  Back in Black      1980  00:42:11

In [43]:
pd_songs.iloc[2]


Artist                     Pink Floyd
Album       The Dark Side of the Moon
Released                         1973
Length                       00:42:49
Name: 2, dtype: object

In [44]:
pd_songs.loc[2]

Artist                     Pink Floyd
Album       The Dark Side of the Moon
Released                         1973
Length                       00:42:49
Name: 2, dtype: object

In [45]:
print(pd_songs)

            Artist                      Album  Released    Length
0  Michael Jackson                   Thriller      1982  00:42:19
1            AC/DC              Back in Black      1980  00:42:11
2       Pink Floyd  The Dark Side of the Moon      1973  00:42:49
3  Whitney Houston              The Bodyguard      1992  00:57:44
4        Meat Loaf            Bat Out of Hell      1977  00:46:33


### Boolean filter (True/False condition)

In [48]:
df1 = pd_songs["Released"] > 1979
print(df1)

0     True
1     True
2    False
3     True
4    False
Name: Released, dtype: bool


### Filter DataFrame with condition



In [49]:
df1 = pd_songs[pd_songs["Released"] > 1979]
print(df1)

            Artist          Album  Released    Length
0  Michael Jackson       Thriller      1982  00:42:19
1            AC/DC  Back in Black      1980  00:42:11
3  Whitney Houston  The Bodyguard      1992  00:57:44


### Unique values Released



In [55]:
pdr = pd_songs["Released"].unique()
print(pdr)

[1982 1980 1973 1992 1977]


### Save the new DataFrame df1 to a file



In [69]:
df1.to_csv("new_songs.csv", index=False)
new_songs = pd.read_csv("new_songs.csv")
new_songs

Artist     Album  Released    Length
0  Michael Jackson  Thriller      1982  00:42:19

### Series creation



In [72]:
serie = pd.Series([10,20,30,40,50])
print(serie)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [73]:
print(serie[1])

20


In [82]:
media = serie.mean()
print(media)

30.0


In [75]:
print(serie.unique())

[10 20 30 40 50]


## Repeat and Understand

In [109]:
import pandas as pd 
file = pd.read_csv("songs.csv")
file.head(3)

Artist                      Album  Released    Length
0  Michael Jackson                   Thriller      1982  00:42:19
1            AC/DC              Back in Black      1980  00:42:11
2       Pink Floyd  The Dark Side of the Moon      1973  00:42:49

In [86]:
file.shape

(5, 4)

In [92]:
pda = file[["Artist"]]
pda

Artist
0  Michael Jackson
1            AC/DC
2       Pink Floyd
3  Whitney Houston
4        Meat Loaf

In [99]:
nfile = file[["Artist","Released"]]
nfile.iloc[[0,1,2]]

Artist  Released
0  Michael Jackson      1982
1            AC/DC      1980
2       Pink Floyd      1973

In [103]:
file.loc[0:2, ["Artist", "Released"]]

Artist  Released
0  Michael Jackson      1982
1            AC/DC      1980
2       Pink Floyd      1973

In [110]:
newfile = file[(file["Released"] <= 1990)  & (file["Released"] >= 1980)]
newfile

Artist          Album  Released    Length
0  Michael Jackson       Thriller      1982  00:42:19
1            AC/DC  Back in Black      1980  00:42:11

In [112]:
newfile.to_csv("songs_80s.csv")

In [117]:
file["Released"].unique()

array([1982, 1980, 1973, 1992, 1977])

In [118]:
file["Released"].nunique()

5

In [121]:
file["Released"].mean()

np.float64(1980.8)

In [123]:
my_new_songs = pd.DataFrame({"Artist": ("Maluma", "Shakira" , "Enrique", "Alvaro") , "Album" : ("Conster" , "Goast " , "Kasti", "Goal") , "Released ": ("2013","2005","1998","2020")})


In [124]:
print(my_new_songs)

    Artist    Album Released 
0   Maluma  Conster      2013
1  Shakira   Goast       2005
2  Enrique    Kasti      1998
3   Alvaro     Goal      2020


In [125]:
my_new_songs.to_csv("my_songs.csv")

In [127]:
copy_new_songs = my_new_songs.copy()

In [128]:
copy_new_songs

Artist    Album Released 
0   Maluma  Conster      2013
1  Shakira   Goast       2005
2  Enrique    Kasti      1998
3   Alvaro     Goal      2020

In [131]:
copy_new_songs.index = ["A","B","C","D"]

In [132]:
copy_new_songs

Artist    Album Released 
A   Maluma  Conster      2013
B  Shakira   Goast       2005
C  Enrique    Kasti      1998
D   Alvaro     Goal      2020

In [134]:
copy_new_songs.loc["A"]

Artist        Maluma
Album        Conster
Released        2013
Name: A, dtype: object