# Two Dimensional Numpy

In [1]:
import numpy as np

In [4]:
a = [[11,12,13], [21,22,23], [31,32,33]]
A = np.array(a) #creamos un array de numpy , ahora si es 2D
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [5]:
A.ndim # 2D

2

In [6]:
A.shape #forma array 3 filas , 3 columnas

(3, 3)

In [7]:
A.size #tamaño

9

In [9]:
A[1][2] 

np.int64(23)

In [14]:
x = np.array([[1,0],[1,0]])
y = np.array([[2,1],[3,0]])
r = x + y
r

array([[3, 1],
       [4, 0]])

In [15]:
rm = x * y
rm

array([[2, 0],
       [3, 0]])

In [17]:
m = np.array([[4,3,9],[5,1,3]])
n = np.array([[4,3],[5,1],[7,2]])
mn = np.dot(m,n)
mn

array([[94, 33],
       [46, 22]])

In [18]:
arr = np.array([4, 9, 16, 25])
rz = result = np.sqrt(arr) # calcula la raíz cuadrada de cada elemento del array
rz

array([2., 3., 4., 5.])

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)  #  cambia la forma del array a 2 filas × 3 columnas
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
transposed_arr = arr.T    # convierte filas en columnas y columnas en filas
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]
